### ISSUE TITLE
Can't run code inside container

### ISSUE THREAD

**Issue by craigbruenderman** [fsedano/cisco_9800_programmability#1]
root@433a5ba70c51:/app/ap_to_site# python change_ap_tag.py
Traceback (most recent call last):
  File "change_ap_tag.py", line 3, in <module>
    from c9800 import C9800
  File "/app/ap_to_site/c9800/__init__.py", line 2, in <module>
    from .wirelesscontroller import C9800
ModuleNotFoundError: No module named 'c9800.wirelesscontroller'
root@433a5ba70c51:/app/ap_to_site#

**Comment by fsedano** [comment]
@craigbruenderman thanks for the report - Will look into it.

**Comment by fsedano** [comment]
@craigbruenderman Fixed, thanks for the report.
